language: java
dist: trusty
addons:
  apt:
    packages:
      - oracle-java8-installer
jdk: oraclejdk8
before_deploy:
#  - git config --global user.email "builds@travis-ci.com"
#  - git config --global user.name "Travis CI"
#  - export GIT_TAG=v2.0.0-b$TRAVIS_BUILD_NUMBER
#  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
#  - git push origin --tags
  - mvn package
deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file: "target/App.jar"
  skip_cleanup: true
  on:
    tags: false